language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source

script: make test

matrix:
  include: 
    - php: hhvm
      dist: trusty
  fast_finish: true